### ISSUE TITLE
 Please provide installation/usage instructions #1 

### ISSUE THREAD

**Issue by rnauber** [OinkIguana/machi-koro#1]
Hi there,
as a total nodejs rookie, I would really like to have foolproof installation instructions for this app. What I tried up until now is:

`npm install https://github.com/OinkIguana/machi-koro.git`

```
bash-4.4$ npm start

> machi-koro@1.0.0 start /data/data/com.termux/files/home/node_modules/machi-koro
> node server.js

module.js:471
    throw err;
    ^

Error: Cannot find module '/data/data/com.termux/files/home/node_modules/machi-koro/server.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3

npm ERR! Linux 3.4.0-perf-gc14c2d5
npm ERR! argv "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/bin/npm" "start"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! machi-koro@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the machi-koro@1.0.0 start script 'node server.js'.
```

and

```
bash-4.4$ ./node_modules/.bin/webpack --config node_modules/machi-koro/webpack.config.js 
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration[0].output.path: The provided value "./public_html" is not an absolute path!
 - configuration[1].output.path: The provided value "./" is not an absolute path!

```

Thank you,
Richard

**Comment by OinkIguana** [comment]
git clone https://github.com/OinkIguana/machi-koro
    cd machi-koro
    npm install
    webpack -p
    npm start

After that, you should be able to see the app running at `localhost:8888`

Ensure that you have webpack installed too. If not, you will need to run `npm install -g webpack` before the webpack step

**Comment by zinovik** [comment]
> git clone https://github.com/OinkIguana/machi-koro

ok

> cd machi-koro

not ok, but `cd node_modules/machi-koro` ok

> npm install

ok

> npm install -g webpack

ok

> webpack -p

not ok
```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration[0].output.path: The provided value "./public_html" is not an absolute path!
 - configuration[1].output.path: The provided value "./" is not an absolute path!
```

i fixed paths in _webpack.config.js_ from `path: './public_html',` and `path: './',` to `path: __dirname + './public_html',` and `path: __dirname + './',`, but still have an error
```
    ERROR in ./src/client/index.js
    Module parse failed: *\node_modules\machi-koro\src\client\index.js Unexpected token (13:2)
    You may need an appropriate loader to handle this file type.
    |
    | render(
    |   <SocketProvider socket={ socket }>
    |     <ReduxProvider store={ store }>
    |       <MachiKoro />
```

> npm start

obviously, not ok
`Error: Cannot find module '*\node_modules\machi-koro\server.js'`

**Comment by OinkIguana** [comment]
Are you sure you used `git clone` correctly? The machi-koro directory should never end up in the node_modules. Maybe you ran `npm install https://github.com/OinkIguana/machi-koro.git` instead, which would cause this problem.

As for those other issues, they are due to some updates in the npm packages. I will bring this repository up to date. 

Please try the instructions below, exactly as listed.

```
git clone https://github.com/OinkIguana/machi-koro
cd machi-koro
npm install
npm run build
npm start
```

Note that the `npm run build` step may take a long time, but it will eventually finish.

**Comment by zinovik** [comment]
Your are right. I didn't use `git clone` correctly. Everything works now. Thank you ;)

**Comment by OinkIguana** [comment]
No problem. I hope you enjoy the game! 😄
