### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by scottygaydos** [OinkIguana/machi-koro#2]
18 verbose node v8.1.2
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error machi-koro@1.0.0 build: `NODE_ENV=production webpack`
22 error Exit status 1
23 error Failed at the machi-koro@1.0.0 build script.

**Comment by OinkIguana** [comment]
It worked for me. Make sure you run `npm install` before `npm run build`
